# -*- coding: utf-8 -*-
"""Licence_Plate_Recognition_YOLO_V8_EasyOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15zKugXvx8tEE8M_sabH40RdFCerlrTOz
"""

!git clone https://github.com/Arijit1080/Licence-Plate-Detection-and-Recognition-using-YOLO-V8-EasyOCR.git

cd /content/Licence-Plate-Detection-and-Recognition-using-YOLO-V8-EasyOCR

pip install -r requirements.txt

!python predictWithOCR.py model='/content/Licence-Plate-Detection-and-Recognition-using-YOLO-V8-EasyOCR/best.pt' source='/content/Licence-Plate-Detection-and-Recognition-using-YOLO-V8-EasyOCR/image1.jpg'